body {
  background-image: linear-gradient(to left, #917f9e, #f3f2f2);
}
nav {
  display: flex;
  flex-direction: row;
  height: 100px;
  border: 1px solid;
  padding: 20px;
  justify-content: space-between;
}
section {
  width: 100%;
}
